version: "3.8"
services:
  master:
    build: .
    container_name: rpc_master
    command: python rpc_master.py --num_workers 2 --addr rpc_master
    networks:
      rpc_network:
        aliases:
          - rpc_master

  worker1:
    build: .
    container_name: rpc_worker1
    command: python rpc_worker.py --rank 1 --world_size 3 --addr rpc_master
    networks:
      rpc_network:
        aliases:
          - rpc_worker1

  worker2:
    build: .
    container_name: rpc_worker2
    command: python rpc_worker.py --rank 2 --world_size 3 --addr rpc_master
    networks:
      rpc_network:
        aliases:
          - rpc_worker2

networks:
  rpc_network:
    driver: bridge
