FROM pytorch/pytorch


RUN pip install Flask
RUN apt-get update && apt-get -y install net-tools


COPY worker.py worker.py
COPY tcp.py tcp.py

# 환경변수 추가
ENV PORT=10001


CMD ["sh", "-c", "python worker.py"]

